#!/bin/sh
# Script to push all your local changes after commit
echo "----------------------------------------------------"
echo "Pushing the commited changes automatically by the post-commit hook..."
echo 
git push --all
echo "----------------------------------------------------"